/**
 * leaderboard-ae.js — Generates a headless After Effects ExtendScript JSX
 * that updates the leaderboard project, renders the MAIN comp with alpha,
 * and writes a sentinel file on completion.
 *
 * Mirrors the logic of update_leaderboard.jsx but runs non-interactively
 * with all values baked into the generated script.
 */

var LeaderboardAE = (function () {
    "use strict";

    // ── AE project constants (must match the AE project structure) ──

    var MAIN_COMP_NAME        = "MAIN";
    var LEADERBOARD_COMP_NAME = "LEADERBOARD";
    var CARDS_FOLDER_NAME     = "03_CARDS";
    var NUMBERS_LAYER_NAME    = "Position Numbers";
    var GUEST_LAYER_INDEX     = 2;
    var CARD_HEIGHT           = 316;
    var START_Y               = 320;

    /**
     * Generate a complete AE ExtendScript JSX string.
     *
     * @param {Object} opts
     * @param {string} opts.aepPath        - Path to the source .aep file
     * @param {string} opts.newName        - New guest name
     * @param {number} opts.newPosition    - New guest rank position
     * @param {number} opts.newScore       - New guest score (%)
     * @param {string} opts.outputAepPath  - Where to Save-As the modified project
     * @param {string} opts.outputMovPath      - Render output .mov path
     * @param {string} opts.outputGridPngPath  - Output path for leaderboard grid PNG
     * @param {string} opts.sentinelPath       - Path to write _lb_done.txt when finished
     * @returns {string} The complete JSX script
     */
    function generateJSX(opts) {
        // Escape backslashes and quotes for embedding in JSX strings
        function jsPath(p) { return p.replace(/\\/g, "/"); }
        function jsStr(s)  { return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/'/g, "\\'"); }

        var aepPath          = jsPath(opts.aepPath);
        var newName          = jsStr(opts.newName);
        var newPosition      = opts.newPosition;
        var newScore         = opts.newScore;
        var outputAepPath    = jsPath(opts.outputAepPath);
        var outputMovPath    = jsPath(opts.outputMovPath);
        var outputGridPngPath = jsPath(opts.outputGridPngPath);
        var sentinelPath     = jsPath(opts.sentinelPath);

        var jsx = '';
        jsx += '// Auto-generated leaderboard update script\n';
        jsx += '// Generated by Paper Editor CEP panel\n';
        jsx += '#target aftereffects\n\n';
        jsx += '(function () {\n\n';

        // ── Constants ──
        jsx += '    var MAIN_COMP_NAME        = "' + MAIN_COMP_NAME + '";\n';
        jsx += '    var LEADERBOARD_COMP_NAME = "' + LEADERBOARD_COMP_NAME + '";\n';
        jsx += '    var CARDS_FOLDER_NAME     = "' + CARDS_FOLDER_NAME + '";\n';
        jsx += '    var NUMBERS_LAYER_NAME    = "' + NUMBERS_LAYER_NAME + '";\n';
        jsx += '    var GUEST_LAYER_INDEX     = ' + GUEST_LAYER_INDEX + ';\n';
        jsx += '    var CARD_HEIGHT           = ' + CARD_HEIGHT + ';\n';
        jsx += '    var START_Y               = ' + START_Y + ';\n\n';

        // ── Parameters ──
        jsx += '    var NEW_NAME     = "' + newName + '";\n';
        jsx += '    var NEW_POSITION = ' + newPosition + ';\n';
        jsx += '    var NEW_SCORE    = ' + newScore + ';\n';
        jsx += '    var AEP_PATH       = "' + aepPath + '";\n';
        jsx += '    var OUTPUT_AEP     = "' + outputAepPath + '";\n';
        jsx += '    var OUTPUT_MOV      = "' + outputMovPath + '";\n';
        jsx += '    var OUTPUT_GRID_PNG = "' + outputGridPngPath + '";\n';
        jsx += '    var SENTINEL_PATH   = "' + sentinelPath + '";\n\n';

        // ── Helper functions ──
        jsx += '    function writeSentinel(msg) {\n';
        jsx += '        var f = new File(SENTINEL_PATH);\n';
        jsx += '        f.open("w");\n';
        jsx += '        f.write(msg || "done");\n';
        jsx += '        f.close();\n';
        jsx += '    }\n\n';

        jsx += '    function getCompByName(name) {\n';
        jsx += '        for (var i = 1; i <= app.project.numItems; i++) {\n';
        jsx += '            var item = app.project.item(i);\n';
        jsx += '            if (item instanceof CompItem && item.name === name) return item;\n';
        jsx += '        }\n';
        jsx += '        return null;\n';
        jsx += '    }\n\n';

        jsx += '    function getFolderByName(name) {\n';
        jsx += '        for (var i = 1; i <= app.project.numItems; i++) {\n';
        jsx += '            var item = app.project.item(i);\n';
        jsx += '            if (item instanceof FolderItem && item.name === name) return item;\n';
        jsx += '        }\n';
        jsx += '        return null;\n';
        jsx += '    }\n\n';

        jsx += '    function findLayerByName(comp, name) {\n';
        jsx += '        for (var i = 1; i <= comp.numLayers; i++) {\n';
        jsx += '            if (comp.layer(i).name === name) return comp.layer(i);\n';
        jsx += '        }\n';
        jsx += '        return null;\n';
        jsx += '    }\n\n';

        jsx += '    function isCardLayer(layer) {\n';
        jsx += '        return layer.name.indexOf("CARD_") === 0;\n';
        jsx += '    }\n\n';

        jsx += '    function getSlider(layer, effectName) {\n';
        jsx += '        try { return layer.effect(effectName).property("Slider").value; }\n';
        jsx += '        catch (e) { return null; }\n';
        jsx += '    }\n\n';

        jsx += '    function setSlider(layer, effectName, val) {\n';
        jsx += '        try { layer.effect(effectName).property("Slider").setValue(val); return true; }\n';
        jsx += '        catch (e) { return false; }\n';
        jsx += '    }\n\n';

        jsx += '    function findFirstCardIndex(comp) {\n';
        jsx += '        for (var i = 1; i <= comp.numLayers; i++) {\n';
        jsx += '            if (isCardLayer(comp.layer(i))) return i;\n';
        jsx += '        }\n';
        jsx += '        return 1;\n';
        jsx += '    }\n\n';

        jsx += '    function countCardLayers(comp) {\n';
        jsx += '        var n = 0;\n';
        jsx += '        for (var i = 1; i <= comp.numLayers; i++) {\n';
        jsx += '            if (isCardLayer(comp.layer(i))) n++;\n';
        jsx += '        }\n';
        jsx += '        return n;\n';
        jsx += '    }\n\n';

        // ── Position expression builder ──
        jsx += '    function buildPositionExpression(firstCardIdx) {\n';
        jsx += '        return [\n';
        jsx += '            \'slider = thisComp.layer("Null 1").effect("Slider Control")("Slider").value;\',\n';
        jsx += '            \'yOffset = Math.min(thisComp.layer("Null 1").transform.position[1], \' + CARD_HEIGHT + \');\',\n';
        jsx += '            \'\',\n';
        jsx += '            \'startY         = \' + START_Y + \';\',\n';
        jsx += '            \'firstCardIndex = \' + firstCardIdx + \';\',\n';
        jsx += '            \'cardHeight     = \' + CARD_HEIGHT + \';\',\n';
        jsx += '            \'\',\n';
        jsx += '            \'origin = [value[0], startY + ((index - firstCardIndex) * cardHeight)];\',\n';
        jsx += '            \'\',\n';
        jsx += '            \'if (index < slider) {\',\n';
        jsx += '            \'    origin;\',\n';
        jsx += '            \'} else {\',\n';
        jsx += '            \'    origin + [0, yOffset];\',\n';
        jsx += '            \'}\'\n';
        jsx += '        ].join("\\n");\n';
        jsx += '    }\n\n';

        // ── Update all card expressions ──
        jsx += '    function updateAllCardExpressions(comp) {\n';
        jsx += '        var idx  = findFirstCardIndex(comp);\n';
        jsx += '        var expr = buildPositionExpression(idx);\n';
        jsx += '        var n    = 0;\n';
        jsx += '        for (var i = 1; i <= comp.numLayers; i++) {\n';
        jsx += '            if (isCardLayer(comp.layer(i))) {\n';
        jsx += '                comp.layer(i).property("Position").expression = expr;\n';
        jsx += '                n++;\n';
        jsx += '            }\n';
        jsx += '        }\n';
        jsx += '        return { count: n, firstCardIndex: idx };\n';
        jsx += '    }\n\n';

        // ── Rank numbering ──
        jsx += '    function updateNumberingLayer(comp, totalPositions) {\n';
        jsx += '        var layer = findLayerByName(comp, NUMBERS_LAYER_NAME);\n';
        jsx += '        if (!layer) return null;\n';
        jsx += '        var lines = [];\n';
        jsx += '        for (var i = 1; i <= totalPositions; i++) lines.push(String(i));\n';
        jsx += '        var src     = layer.property("Source Text");\n';
        jsx += '        var textDoc = src.value;\n';
        jsx += '        textDoc.text = lines.join("\\r");\n';
        jsx += '        src.setValue(textDoc);\n';
        jsx += '        return layer.name;\n';
        jsx += '    }\n\n';

        // ── Null 1 keyframe repair ──
        jsx += '    function fixNull1PositionKeyframes(null1Layer) {\n';
        jsx += '        var pos     = null1Layer.property("Position");\n';
        jsx += '        var numKeys = pos.numKeys;\n';
        jsx += '        if (numKeys < 2) {\n';
        jsx += '            var cur = pos.value;\n';
        jsx += '            if (cur[1] !== 0) pos.setValue([cur[0], 0]);\n';
        jsx += '            return;\n';
        jsx += '        }\n';
        jsx += '        var keys = [];\n';
        jsx += '        for (var i = 1; i <= numKeys; i++) {\n';
        jsx += '            keys.push({ time: pos.keyTime(i), value: pos.keyValue(i) });\n';
        jsx += '        }\n';
        jsx += '        var firstY = keys[0].value[1];\n';
        jsx += '        var lastY  = keys[keys.length - 1].value[1];\n';
        jsx += '        if (Math.round(firstY) === 0 && Math.round(lastY) === CARD_HEIGHT) return;\n';
        jsx += '        var range = lastY - firstY;\n';
        jsx += '        for (var j = 0; j < keys.length; j++) {\n';
        jsx += '            var newY;\n';
        jsx += '            if (range === 0) {\n';
        jsx += '                newY = (j === keys.length - 1) ? CARD_HEIGHT : 0;\n';
        jsx += '            } else {\n';
        jsx += '                newY = ((keys[j].value[1] - firstY) / range) * CARD_HEIGHT;\n';
        jsx += '            }\n';
        jsx += '            pos.setValueAtTime(keys[j].time, [keys[j].value[0], newY]);\n';
        jsx += '        }\n';
        jsx += '    }\n\n';

        // ── Expression name replacement ──
        jsx += '    function scanPropertyGroup(group, oldName, newName) {\n';
        jsx += '        var count = 0;\n';
        jsx += '        for (var i = 1; i <= group.numProperties; i++) {\n';
        jsx += '            var prop = group.property(i);\n';
        jsx += '            if (prop.propertyType === PropertyType.PROPERTY) {\n';
        jsx += '                if (prop.canSetExpression && prop.expressionEnabled && prop.expression !== "") {\n';
        jsx += '                    if (prop.expression.indexOf(oldName) !== -1) {\n';
        jsx += '                        prop.expression = prop.expression.split(oldName).join(newName);\n';
        jsx += '                        count++;\n';
        jsx += '                    }\n';
        jsx += '                }\n';
        jsx += '            } else if (prop.propertyType === PropertyType.INDEXED_GROUP ||\n';
        jsx += '                       prop.propertyType === PropertyType.NAMED_GROUP) {\n';
        jsx += '                count += scanPropertyGroup(prop, oldName, newName);\n';
        jsx += '            }\n';
        jsx += '        }\n';
        jsx += '        return count;\n';
        jsx += '    }\n\n';

        jsx += '    function updateAllExpressions(oldName, newName) {\n';
        jsx += '        var total = 0;\n';
        jsx += '        for (var i = 1; i <= app.project.numItems; i++) {\n';
        jsx += '            if (app.project.item(i) instanceof CompItem) {\n';
        jsx += '                var comp = app.project.item(i);\n';
        jsx += '                for (var j = 1; j <= comp.numLayers; j++) {\n';
        jsx += '                    total += scanPropertyGroup(comp.layer(j), oldName, newName);\n';
        jsx += '                }\n';
        jsx += '            }\n';
        jsx += '        }\n';
        jsx += '        return total;\n';
        jsx += '    }\n\n';

        // ═══════════════════════════════════════════
        //  MAIN EXECUTION
        // ═══════════════════════════════════════════

        jsx += '    // ═══════════════════════════════════════════\n';
        jsx += '    //  MAIN EXECUTION\n';
        jsx += '    // ═══════════════════════════════════════════\n\n';

        jsx += '    try {\n';
        jsx += '        app.beginSuppressDialogs();\n\n';

        // Open the AEP
        jsx += '        // Open AEP\n';
        jsx += '        var aepFile = new File(AEP_PATH);\n';
        jsx += '        if (!aepFile.exists) {\n';
        jsx += '            writeSentinel("ERROR: AEP file not found: " + AEP_PATH);\n';
        jsx += '            return;\n';
        jsx += '        }\n';
        jsx += '        app.open(aepFile);\n\n';

        // Find comps
        jsx += '        var mainComp = getCompByName(MAIN_COMP_NAME);\n';
        jsx += '        if (!mainComp) {\n';
        jsx += '            writeSentinel("ERROR: Could not find comp: " + MAIN_COMP_NAME);\n';
        jsx += '            return;\n';
        jsx += '        }\n';
        jsx += '        var leaderboardComp = getCompByName(LEADERBOARD_COMP_NAME);\n';
        jsx += '        if (!leaderboardComp) {\n';
        jsx += '            writeSentinel("ERROR: Could not find comp: " + LEADERBOARD_COMP_NAME);\n';
        jsx += '            return;\n';
        jsx += '        }\n\n';

        // Read previous guest
        jsx += '        var guestLayer = mainComp.layer(GUEST_LAYER_INDEX);\n';
        jsx += '        if (!guestLayer) {\n';
        jsx += '            writeSentinel("ERROR: Could not find layer " + GUEST_LAYER_INDEX + " in " + MAIN_COMP_NAME);\n';
        jsx += '            return;\n';
        jsx += '        }\n';
        jsx += '        var previousGuestName = guestLayer.name;\n';
        jsx += '        var previousPosition  = getSlider(guestLayer, "Position");\n';
        jsx += '        var rankPosition      = previousPosition !== null ? Math.round(previousPosition) : 1;\n\n';

        // Begin undo group
        jsx += '        app.beginUndoGroup("Update Leaderboard - " + NEW_NAME);\n\n';

        // Step 1: Create CARD_ comp for previous guest
        jsx += '        // Step 1: Create CARD_ comp for previous guest\n';
        jsx += '        var templateCard = null;\n';
        jsx += '        for (var i = 1; i <= app.project.numItems; i++) {\n';
        jsx += '            var item = app.project.item(i);\n';
        jsx += '            if (item instanceof CompItem && item.name.indexOf("CARD_") === 0) {\n';
        jsx += '                templateCard = item;\n';
        jsx += '                break;\n';
        jsx += '            }\n';
        jsx += '        }\n';
        jsx += '        if (!templateCard) {\n';
        jsx += '            writeSentinel("ERROR: No existing CARD_ comp to use as template");\n';
        jsx += '            app.endUndoGroup();\n';
        jsx += '            return;\n';
        jsx += '        }\n\n';

        jsx += '        var newCard = templateCard.duplicate();\n';
        jsx += '        newCard.name = "CARD_" + previousGuestName;\n\n';

        jsx += '        var cardTextLayer = newCard.layer(1);\n';
        jsx += '        if (cardTextLayer && cardTextLayer.property("Source Text") !== null) {\n';
        jsx += '            var textDoc = cardTextLayer.property("Source Text").value;\n';
        jsx += '            textDoc.text = previousGuestName;\n';
        jsx += '            cardTextLayer.property("Source Text").setValue(textDoc);\n';
        jsx += '            cardTextLayer.name = previousGuestName;\n';
        jsx += '        }\n\n';

        jsx += '        var cardsFolder = getFolderByName(CARDS_FOLDER_NAME);\n';
        jsx += '        if (cardsFolder) newCard.parentFolder = cardsFolder;\n\n';

        // Step 2: Add CARD_ to LEADERBOARD
        jsx += '        // Step 2: Add CARD_ to LEADERBOARD at rank\n';
        jsx += '        var cardLayer = leaderboardComp.layers.add(newCard);\n';
        jsx += '        cardLayer.property("Anchor Point").setValue([3240, 0]);\n\n';

        jsx += '        if (rankPosition > 1 && rankPosition <= leaderboardComp.numLayers) {\n';
        jsx += '            cardLayer.moveAfter(leaderboardComp.layer(rankPosition));\n';
        jsx += '        }\n\n';

        // Step 3: Rebuild expressions + Null 1
        jsx += '        // Step 3: Rebuild expressions + Null 1\n';
        jsx += '        updateAllCardExpressions(leaderboardComp);\n\n';

        jsx += '        var totalPositions = countCardLayers(leaderboardComp) + 1;\n';
        jsx += '        updateNumberingLayer(leaderboardComp, totalPositions);\n\n';

        jsx += '        var null1 = findLayerByName(leaderboardComp, "Null 1");\n';
        jsx += '        if (null1) {\n';
        jsx += '            setSlider(null1, "Slider Control", NEW_POSITION);\n';
        jsx += '            fixNull1PositionKeyframes(null1);\n';
        jsx += '        }\n\n';

        // Step 4: Update layer 2 in MAIN
        jsx += '        // Step 4: Update layer 2 in MAIN with new guest\n';
        jsx += '        guestLayer.name = NEW_NAME;\n';
        jsx += '        setSlider(guestLayer, "Position", NEW_POSITION);\n';
        jsx += '        setSlider(guestLayer, "Percentage", NEW_SCORE);\n\n';

        // Step 5: Replace old guest name in expressions
        jsx += '        // Step 5: Replace old guest name in expressions\n';
        jsx += '        updateAllExpressions(previousGuestName, NEW_NAME);\n\n';

        jsx += '        app.endUndoGroup();\n\n';

        // Step 6: Save-As
        jsx += '        // Step 6: Save project copy\n';
        jsx += '        app.project.save(new File(OUTPUT_AEP));\n\n';

        // Step 7: Render MAIN comp as QuickTime ProRes 4444 .mov with RGB+Alpha at 1920x1080
        jsx += '        // Step 7: Install output template if needed, then render\n';
        jsx += '        var PE_TEMPLATE = "Paper Editor ProRes4444 Alpha";\n';
        jsx += '        var codecWarning = "";\n\n';

        // Install our custom template if it doesn't already exist
        jsx += '        // Check if our template is already installed\n';
        jsx += '        var templateExists = false;\n';
        jsx += '        (function () {\n';
        jsx += '            while (app.project.renderQueue.numItems > 0)\n';
        jsx += '                app.project.renderQueue.item(1).remove();\n';
        jsx += '            var tmpRQ = app.project.renderQueue.items.add(mainComp);\n';
        jsx += '            var tmpOM = tmpRQ.outputModule(1);\n';
        jsx += '            var tpls  = tmpOM.templates;\n';
        jsx += '            for (var ti = 0; ti < tpls.length; ti++) {\n';
        jsx += '                if (tpls[ti] === PE_TEMPLATE) { templateExists = true; break; }\n';
        jsx += '            }\n';
        jsx += '            if (!templateExists) {\n';
        jsx += '                // Start from "High Quality with Alpha" (QuickTime, Animation, RGB+Alpha)\n';
        jsx += '                tmpOM.applyTemplate("High Quality with Alpha");\n';
        jsx += '                // Upgrade codec to ProRes 4444 via SPEC settings\n';
        jsx += '                try {\n';
        jsx += '                    var spec = tmpOM.getSettings(GetSettingsFormat.SPEC);\n';
        jsx += '                    spec["VideoCodec"] = "ap4h";\n';
        jsx += '                    tmpOM.setSettings(spec);\n';
        jsx += '                    tmpOM = tmpRQ.outputModule(1);\n';
        jsx += '                } catch (codecErr) {\n';
        jsx += '                    codecWarning = "WARNING: ProRes 4444 not available — falling back to Animation codec (larger file). Error: " + codecErr.message;\n';
        jsx += '                }\n';
        jsx += '                // Set resize to 1920x1080\n';
        jsx += '                try {\n';
        jsx += '                    tmpOM.setSettings({\n';
        jsx += '                        "Resize": "ON",\n';
        jsx += '                        "Resize to": { "0": 1920, "1": 1080 }\n';
        jsx += '                    });\n';
        jsx += '                    tmpOM = tmpRQ.outputModule(1);\n';
        jsx += '                } catch (resizeErr) {}\n';
        jsx += '                tmpOM.saveAsTemplate(PE_TEMPLATE);\n';
        jsx += '            }\n';
        jsx += '            tmpRQ.remove();\n';
        jsx += '        })();\n\n';

        // Now set up the real render
        jsx += '        var rqItem = app.project.renderQueue.items.add(mainComp);\n';
        jsx += '        var om = rqItem.outputModule(1);\n';
        jsx += '        om.applyTemplate(PE_TEMPLATE);\n\n';

        jsx += '        om.file = new File(OUTPUT_MOV);\n\n';
        jsx += '        // Force software rendering to avoid GPU memory limitations\n';
        jsx += '        app.project.gpuAccelType = GpuAccelType.SOFTWARE;\n\n';
        jsx += '        app.project.renderQueue.render();\n\n';

        // Save again after render
        jsx += '        app.project.save();\n\n';

        // Step 8: Build LEADERBOARD_GRID comp and export as transparent PNG
        jsx += '        // Step 8: Build LEADERBOARD_GRID comp and export as PNG\n';
        jsx += '        var gridPngOk = false;\n';
        jsx += '        try {\n';
        jsx += '            var GRID_W   = 1920, GRID_H = 1080, GRID_COLS = 3;\n';
        jsx += '            var GRID_PAD = 50, GRID_GAP = 2, GRID_NUM_GAP = 6;\n\n';

        // Collect CARD_ comps from leaderboardComp in layer order
        jsx += '            var gridCards = [];\n';
        jsx += '            for (var gl = 1; gl <= leaderboardComp.numLayers; gl++) {\n';
        jsx += '                var gsrc = leaderboardComp.layer(gl).source;\n';
        jsx += '                if (gsrc && gsrc instanceof CompItem && gsrc.name.indexOf("CARD_") === 0) {\n';
        jsx += '                    gridCards.push(gsrc);\n';
        jsx += '                }\n';
        jsx += '            }\n\n';

        // Scan for crop bounds (exclude % score text)
        jsx += '            if (gridCards.length > 0) {\n';
        jsx += '                var gcW = gridCards[0].width, gcH = gridCards[0].height;\n';
        jsx += '                var gLeft = Infinity, gRight = -Infinity;\n\n';

        jsx += '                for (var gc = 0; gc < gridCards.length; gc++) {\n';
        jsx += '                    var gcc = gridCards[gc];\n';
        jsx += '                    for (var gcl = 1; gcl <= gcc.numLayers; gcl++) {\n';
        jsx += '                        var glay = gcc.layer(gcl);\n';
        jsx += '                        var gst = null;\n';
        jsx += '                        try { gst = glay.property("Source Text"); } catch(e) {}\n';
        jsx += '                        if (!gst) continue;\n';
        jsx += '                        var gtxt = gst.value.text;\n';
        jsx += '                        if (gtxt.indexOf("%") >= 0) continue;\n';
        jsx += '                        var gr = glay.sourceRectAtTime(0, false);\n';
        jsx += '                        var gp = glay.transform.position.value;\n';
        jsx += '                        var ga = glay.transform.anchorPoint.value;\n';
        jsx += '                        var gs = glay.transform.scale.value;\n';
        jsx += '                        var gl2 = gp[0] + (gr.left - ga[0]) * gs[0] / 100;\n';
        jsx += '                        var gr2 = gp[0] + (gr.left + gr.width - ga[0]) * gs[0] / 100;\n';
        jsx += '                        if (gl2 < gLeft) gLeft = gl2;\n';
        jsx += '                        if (gr2 > gRight) gRight = gr2;\n';
        jsx += '                    }\n';
        jsx += '                }\n\n';

        // Calculate crop, columns, scaling
        jsx += '                var cropL = Math.max(0, Math.floor(gLeft - GRID_PAD));\n';
        jsx += '                var cropR = Math.min(gcW, Math.ceil(gRight + GRID_PAD));\n';
        jsx += '                var cropW = cropR - cropL;\n\n';

        jsx += '                var nCards = gridCards.length;\n';
        jsx += '                var colCts = [], rem = nCards;\n';
        jsx += '                for (var cc = 0; cc < GRID_COLS; cc++) {\n';
        jsx += '                    var rc = GRID_COLS - cc;\n';
        jsx += '                    colCts.push(Math.ceil(rem / rc));\n';
        jsx += '                    rem -= colCts[cc];\n';
        jsx += '                }\n';
        jsx += '                var maxPC = colCts[0];\n\n';

        jsx += '                var tGapX = GRID_GAP * (GRID_COLS - 1);\n';
        jsx += '                var tGapY = GRID_GAP * Math.max(0, maxPC - 1);\n';
        jsx += '                var approxH = (GRID_H - tGapY) / maxPC;\n';
        jsx += '                var fSize = Math.max(8, Math.round(Math.min(approxH * 0.55, 24)));\n';
        jsx += '                var nMarg = Math.ceil(fSize * 3.2) + GRID_NUM_GAP;\n';
        jsx += '                var gCellW = (GRID_W - tGapX - GRID_COLS * nMarg) / GRID_COLS;\n';
        jsx += '                var gCellH = (GRID_H - tGapY) / maxPC;\n';
        jsx += '                var sf = Math.min(gCellW / cropW, gCellH / gcH);\n';
        jsx += '                var sW = cropW * sf, sH = gcH * sf;\n';
        jsx += '                var colSpan = nMarg + sW;\n';
        jsx += '                var gtW = GRID_COLS * colSpan + (GRID_COLS - 1) * GRID_GAP;\n';
        jsx += '                var gtH = maxPC * sH + (maxPC - 1) * GRID_GAP;\n';
        jsx += '                var oX = (GRID_W - gtW) / 2, oY = (GRID_H - gtH) / 2;\n\n';

        // Remove existing LEADERBOARD_GRID comp if present
        jsx += '                for (var ri = app.project.numItems; ri >= 1; ri--) {\n';
        jsx += '                    var rItem = app.project.item(ri);\n';
        jsx += '                    if (rItem instanceof CompItem && rItem.name === "LEADERBOARD_GRID") rItem.remove();\n';
        jsx += '                }\n';

        // Create grid comp
        jsx += '                var gridComp = app.project.items.addComp(\n';
        jsx += '                    "LEADERBOARD_GRID", GRID_W, GRID_H, 1, 1, gridCards[0].frameRate\n';
        jsx += '                );\n\n';

        // Place cards with masks
        jsx += '                var gIdx = 0;\n';
        jsx += '                for (var col = 0; col < GRID_COLS; col++) {\n';
        jsx += '                    for (var row = 0; row < colCts[col]; row++) {\n';
        jsx += '                        if (gIdx >= nCards) break;\n';
        jsx += '                        var cLay = gridComp.layers.add(gridCards[gIdx]);\n';
        jsx += '                        var mGrp = cLay.property("ADBE Mask Parade");\n';
        jsx += '                        var nMsk = mGrp.addProperty("ADBE Mask Atom");\n';
        jsx += '                        var mShp = new Shape();\n';
        jsx += '                        mShp.vertices = [[cropL,0],[cropR,0],[cropR,gcH],[cropL,gcH]];\n';
        jsx += '                        mShp.closed = true;\n';
        jsx += '                        nMsk.property("ADBE Mask Shape").setValue(mShp);\n';
        jsx += '                        cLay.transform.anchorPoint.setValue([cropL + cropW/2, gcH/2]);\n';
        jsx += '                        cLay.transform.scale.setValue([sf*100, sf*100]);\n';
        jsx += '                        var cx = oX + col*(colSpan+GRID_GAP) + nMarg + sW/2;\n';
        jsx += '                        var cy = oY + row*(sH+GRID_GAP) + sH/2;\n';
        jsx += '                        cLay.transform.position.setValue([cx, cy]);\n';
        jsx += '                        gIdx++;\n';
        jsx += '                    }\n';
        jsx += '                }\n\n';

        // Add position numbers (one text layer per column)
        jsx += '                var gLeading = Math.round(sH + GRID_GAP);\n';
        jsx += '                for (var col = 0; col < GRID_COLS; col++) {\n';
        jsx += '                    var sRank = 0;\n';
        jsx += '                    for (var pc = 0; pc < col; pc++) sRank += colCts[pc];\n';
        jsx += '                    var nLines = [];\n';
        jsx += '                    for (var nr = 0; nr < colCts[col]; nr++) nLines.push(String(sRank+nr+1));\n';
        jsx += '                    var nLay = gridComp.layers.addText(nLines.join("\\r"));\n';
        jsx += '                    nLay.name = "Numbers_col" + (col+1);\n';
        jsx += '                    var ntd = nLay.property("Source Text").value;\n';
        jsx += '                    ntd.fontSize = fSize;\n';
        jsx += '                    ntd.leading = gLeading;\n';
        jsx += '                    ntd.fillColor = [1, 1, 1];\n';
        jsx += '                    ntd.justification = ParagraphJustification.RIGHT_JUSTIFY;\n';
        jsx += '                    nLay.property("Source Text").setValue(ntd);\n';
        jsx += '                    var nRect = nLay.sourceRectAtTime(0, false);\n';
        jsx += '                    nLay.transform.anchorPoint.setValue([nRect.left+nRect.width, nRect.top+fSize*0.45]);\n';
        jsx += '                    nLay.transform.position.setValue([\n';
        jsx += '                        oX + col*(colSpan+GRID_GAP) + nMarg - GRID_NUM_GAP,\n';
        jsx += '                        oY + sH/2\n';
        jsx += '                    ]);\n';
        jsx += '                }\n\n';

        // Export as transparent PNG
        jsx += '                gridComp.saveFrameToPng(0, new File(OUTPUT_GRID_PNG));\n';
        jsx += '                gridPngOk = true;\n';

        jsx += '            } // end if gridCards.length > 0\n';
        jsx += '        } catch (gridErr) {\n';
        jsx += '            // Grid is non-critical — log but continue\n';
        jsx += '            gridPngOk = false;\n';
        jsx += '        }\n\n';

        // Write sentinel (include grid PNG path if successful, codec warning if applicable)
        jsx += '        var sentinel = "";\n';
        jsx += '        if (codecWarning) sentinel += codecWarning + "\\n";\n';
        jsx += '        sentinel += "done\\n" + OUTPUT_MOV;\n';
        jsx += '        if (gridPngOk) sentinel += "\\n" + OUTPUT_GRID_PNG;\n';
        jsx += '        writeSentinel(sentinel);\n\n';

        jsx += '    } catch (err) {\n';
        jsx += '        try { app.endUndoGroup(); } catch(e) {}\n';
        jsx += '        writeSentinel("ERROR: " + err.message + " (line " + err.line + ")");\n';
        jsx += '    } finally {\n';
        jsx += '        try { app.endSuppressDialogs(false); } catch(e) {}\n';
        jsx += '    }\n\n';

        jsx += '})();\n';

        return jsx;
    }

    return {
        generateJSX: generateJSX
    };
})();
